### ISSUE TITLE
Cannot Add Page via Pages

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#13] opened 2018-06-29 21:44 UTC
When I go to `Admin | CMS Configuration | Pages` and try to use _Add Child to Selected_ on any existing page, an exception is thrown. All I'm doing is giving the page a Internal Name and clicking Save.
![image](https://user-images.githubusercontent.com/3903408/42116114-800f5c8e-7bbb-11e8-8203-be660da502c6.png)
I can add a page from the Child Pages icon in the Admin Toolbar just fine.

**Comment by ethan-sparkdevnetwork** [comment] 2018-07-02 22:09
I cannot reproduce this one either. Can you provide the exception and URL (with params)?

**Comment by JimMichael** [comment] 2018-07-03 14:21
I cannot reproduce it anymore, either. Maybe I just needed a restart after upgrade to get it working...  Closing.

**Comment by JimMichael** [comment] 2018-07-03 14:23
Oops, spoke too soon... forgot that it only happens after hitting Save. Here's the URL Parameter that causes an exception (but any new page does it, too) https://jimrock.wcrossing.org/page/103?Page=0&ParentPageId=17&ExpandedIds=12%2c44%2c49%2c353

Exception: ```at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Rock.Cache.EntityCache`2.QueryDbWithContext(Int32 id, DbContext rockContext)
   at Rock.Cache.EntityCache`2.QueryDb(Int32 id, DbContext rockContext)
   at Rock.Cache.EntityCache`2.<>c__DisplayClass24_0.<Get>b__0()
   at Rock.Cache.ItemCache`1.GetOrAddExisting(String key, Func`1 itemFactory, TimeSpan expiration)
   at Rock.Cache.ItemCache`1.GetOrAddExisting(Int32 key, Func`1 itemFactory)
   at Rock.Cache.EntityCache`2.Get(Int32 id, RockContext rockContext)
   at Rock.Model.Page.UpdateCache(EntityState entityState, DbContext dbContext)
   at Rock.Data.DbContext.RockPostSave(List`1 updatedItems, PersonAlias personAlias, Boolean enableAuditing)
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
   at RockWeb.Blocks.Administration.PageProperties.<>c__DisplayClass18.<masterPage_OnSave>b__e()
   at Rock.Data.DbContext.WrapTransaction(Action action)
   at RockWeb.Blocks.Administration.PageProperties.masterPage_OnSave(Object sender, EventArgs e)
   at RockWeb.Blocks.Administration.PageProperties.btnSave_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at RockWeb.Global.Application_Error(Object sender, EventArgs e)```

**Comment by cabal95** [comment] 2018-07-04 00:09
Confirmed on my install.

**Comment by cabal95** [comment] 2018-07-04 00:30
@ethan-sparkdevnetwork 

Okay, this seems to be caused by the new caching.  Here is whats happening.

1. The PageProperties block is wrapping the page save in a context.
2. The DbContext.RockPostSave() call's the `Page` model's `UpdateCache` method, passing the current context.
3. The `Page.UpdateCache` method calls the `CachePage.Get(id)` method, which does not get the current context passed.
4. Because the method is not overridden, what is actually called is `EntityCache.Get(id)`.
5. This method calls the `EntityCache.Get(id, null)` method to indicate that no rock context was passed (oops!!!!)
6. `EntityCache.Get(id, RockContext context)` then, through an eventual call to QueryDb, creates a NEW context to load the Page from the DB - but it can't because the table is locked by the original RockContext.
7. Timeout happens, with no CPU usage since it's just waiting for the lock to release.

Probably any `UpdateCache` calls that touch the `.Get(id)` method need to be replaced with `.Get(id, ctx)` method calls instead.

**Comment by ethan-sparkdevnetwork** [comment] 2018-07-05 22:31
Issue occurs on DBs with Is Read Committed On set to false for transactions inside a commit. Updated  classes that use the Cache*.Get() method to also pass the context to prevent the locking behavior. Fixed in 9e2108c7.

**Closed** 2018-07-05 22:32 UTC
Labels: Fixed in 8.0, bug
