### ISSUE TITLE
Personal Merge Template list is incomplete

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#24] opened 2018-07-09 21:58 UTC
When adding a personal merge template _either_ through `Admin Tools -> General Settings -> Merge Templates` or through `My Settings -> Merge Templates`, the new personal template does not show up in the My Settings -> Merge Templates list. Instead, only global templates are listed.

(Note: Templates assigned to others do not show up for administrators on the General Settings -> Merge Templates page, either, but perhaps that's by design?)

Opening the filter configuration and clearing the (visually empty) `Person` dropdown by clicking the `x` link and then clicking `Apply Filter` results in _all_ users' personal merge templates being listed, and _no_ global templates are listed any longer, which conflicts with the block settings tooltip indicating that edit rights to the block will result in global and personal templates being displayed regardless of the block setting.

**A suggestion**
The behavior would be more consistent if this block displayed the chosen type of merge template (global vs personal) for _all_ users, regardless of rights. Perhaps a new page could be added as a child of General Settings -> Merge Templates which would have this same block inserted, but with "Global and Personal" templates selected in the block settings instead, so that _all_ of the templates on the system could be managed from Admin Tools instead of from "My Settings".

**Comment by edmistj** [comment] 2018-07-09 23:54
Implementation Recommendations
1. Definitely need to fix. The issue is in the if logic around edit access. It's trumping the block settings.
2. Would recommend only showing the 'Show Global Merge Templates' filter when owership block setting is set to 'Personal And Global'.
3. I would add this to the future features list.

**Comment by shivambareria** [comment] 2018-07-19 16:13
Fixed in https://github.com/SparkDevNetwork/Rock/commit/50a99ec0b5e4eecf6aa8311ae197c6f4d4de1455.

**Closed by shivambareria** 2018-07-19 16:13 UTC
